/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreIndexRouteImport } from './routes/store.index'
import { Route as StoreProductSlugRouteImport } from './routes/store.$productSlug'
import { Route as PayCodeRouteImport } from './routes/pay.$code'
import { Route as OrderCodeRouteImport } from './routes/order.$code'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductSlugRoute = StoreProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => StoreRoute,
} as any)
const PayCodeRoute = PayCodeRouteImport.update({
  id: '/pay/$code',
  path: '/pay/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/store': typeof StoreRouteWithChildren
  '/order/$code': typeof OrderCodeRoute
  '/pay/$code': typeof PayCodeRoute
  '/store/$productSlug': typeof StoreProductSlugRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/order/$code': typeof OrderCodeRoute
  '/pay/$code': typeof PayCodeRoute
  '/store/$productSlug': typeof StoreProductSlugRoute
  '/store': typeof StoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/store': typeof StoreRouteWithChildren
  '/order/$code': typeof OrderCodeRoute
  '/pay/$code': typeof PayCodeRoute
  '/store/$productSlug': typeof StoreProductSlugRoute
  '/store/': typeof StoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/store'
    | '/order/$code'
    | '/pay/$code'
    | '/store/$productSlug'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/order/$code'
    | '/pay/$code'
    | '/store/$productSlug'
    | '/store'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/store'
    | '/order/$code'
    | '/pay/$code'
    | '/store/$productSlug'
    | '/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  StoreRoute: typeof StoreRouteWithChildren
  OrderCodeRoute: typeof OrderCodeRoute
  PayCodeRoute: typeof PayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/store/$productSlug': {
      id: '/store/$productSlug'
      path: '/$productSlug'
      fullPath: '/store/$productSlug'
      preLoaderRoute: typeof StoreProductSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/pay/$code': {
      id: '/pay/$code'
      path: '/pay/$code'
      fullPath: '/pay/$code'
      preLoaderRoute: typeof PayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoreRouteChildren {
  StoreProductSlugRoute: typeof StoreProductSlugRoute
  StoreIndexRoute: typeof StoreIndexRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreProductSlugRoute: StoreProductSlugRoute,
  StoreIndexRoute: StoreIndexRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  StoreRoute: StoreRouteWithChildren,
  OrderCodeRoute: OrderCodeRoute,
  PayCodeRoute: PayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
